version: '2'
services:
  pharmastatusexternals-mongodb:
    image: mongo:4.0.10
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/PharmaStatusExternals/mongodb/:/data/db/
